name: intention-fitb
variables:
  PYTHONPATH: .
dependencies:
  - pip:
    # `av` from conda-forge uses an ffmpeg version from the same Conda channel that doesn't have the AV codecs
    # (which some of our videos use). See https://github.com/conda-forge/ffmpeg-feedstock/pull/98
    -            av==8.0.3
    # We could use the Conda channel "HuggingFace".
    # However, `tokenizers` was compiled with glibc 2.18, while Great Lakes has 2.17.
    # See https://github.com/huggingface/tokenizers/issues/585
    # There are some non-popular glibc packages available in Anaconda, but Python needs to be linked to it as well.
    # This is cumbersome, so we just use pip.
    -            transformers==4.6.0
  -              boto3=1.17.46  # For `cached_path`.
  -              botocore=1.20.50  # For `cached_path`.
  - conda-forge::cudatoolkit=11.1.1
  -              numpy=1.20.1
  - conda-forge::overrides=3.1.0
  -              pandas=1.2.4
  -              pip=21
  -              python=3.8
  -     pytorch::pytorch=1.8.1
  - conda-forge::pytorch-lightning=1.3.0
  - conda-forge::rarfile=4.0  # For `cached_path`.
  - conda-forge::scikit-learn=0.24.2
  - conda-forge::tensorboard=2.4.1
  - conda-forge::torchmetrics=0.3.2
  -     pytorch::torchvision=0.9.1
  -              tqdm=4.59.0
